DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS PATIENT CASCADE;
DROP TABLE IF EXISTS DOCTOR CASCADE;
DROP TABLE IF EXISTS USER_ROLE CASCADE;
DROP TABLE IF EXISTS Speciality CASCADE;


CREATE TABLE IF NOT EXISTS USER_ROLE
(
    id     SERIAL UNIQUE ,
    authorities VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS
(
    id              SERIAL PRIMARY KEY,
    username        VARCHAR(255) NOT NULL unique ,
    password        VARCHAR(255) NOT NULL,
    authorities_id     integer,
    FOREIGN KEY (authorities_id) REFERENCES USER_ROLE (id) ON UPDATE CASCADE ON DELETE CASCADE
);




CREATE TABLE IF NOT EXISTS DOCTOR
(
    id SERIAL PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES USERS (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Speciality
(
    user_id    INTEGER UNIQUE,
    FOREIGN KEY (user_id) REFERENCES DOCTOR (id) ON UPDATE CASCADE ON DELETE CASCADE,
    speciality VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS PATIENT
(
    id               integer PRIMARY KEY references USERS,
    iscurrentpatient boolean default false,
    birthDate        date not null,
    doctor_id        integer,
    FOREIGN KEY (doctor_id) REFERENCES DOCTOR (id)
);
CREATE INDEX birthDate_index ON PATIENT (birthDate);
